name: publish nuget package
on:
  workflow_run:
    workflows: ["build and test"]
    branches: [ main ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.103
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish to NuGet
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EfCore.Extensions/EfCore.Extensions.csproj
          TAG_FORMAT: '*'
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

